spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user-name
    password: strong-password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        format_sql: true
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: aeneas.nicholas@gmail.com
    password: pbab ftwt erva zggi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  server:
    tomcat:
      remote-ip-header: X-Forwarded-For
  ipinfo:
    token: 300a19e6ae2ffe
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB