spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user-name
    password: strong-password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        format_sql: true
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true