spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user-name
    password: strong-password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        format_sql: true
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true